backend:
  name: git-gateway
  branch: main # Remplace "main" par le nom de ta branche principale si nécessaire

media_folder: "../img"
public_folder: "../img"

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
