backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/static/img/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "../articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Contenu", widget: "markdown" }
