backend:
  name: git-gateway
  branch: main # ou la branche que tu utilises

media_folder: "static/img/uploads" # Dossier où les images seront stockées
public_folder: "/img/uploads" 

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
