backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
public_folder: "images"
collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de Publication", name: "date", widget: "datetime" }
      - { label: "Image à la Une", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", summary: "{{fields.tag}}", field: { label: "Tag", name: "tag", widget: "string" } }
      - { label: "Corps", name: "body", widget: "markdown" }
