backend:
  name: git-gateway
  branch: main # Changez cela en fonction de votre branche principale

media_folder: "assets/images" # Dossier pour les images
public_folder: "/assets/images" # URL publique pour les images

collections:
  - name: "posts" # Nom de la collection
    label: "Articles de Blog" # Label pour l'interface
    folder: "content/blog" # Dossier où les articles seront stockés
    create: true # Permet de créer de nouveaux articles
    fields: # Champs de chaque article
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
