collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - name: "date"
        label: "Date"
        widget: "datetime"
        format: "YYYY-MM-DD"       # Format d'enregistrement dans le fichier
        date_format: "YYYY-MM-DD"  # Format affiché dans le CMS
        time_format: false         # Désactive l'heure
      - { name: "body", label: "Contenu", widget: "markdown" }
